-- Line / Equipments

CREATE TABLE Line(
	LineID INT IDENTITY(1,1) PRIMARY KEY,
	UnitID INT NOT NULL,
	LineName NVARCHAR(100) NOT NULL,
	Material NVARCHAR(50) NULL,
	Diameter DECIMAL(10, 2) NULL,
	CONSTRAINT FK_Line_Unit FOREIGN KEY (UnitID) REFERENCES Unit(UnitID)
);